### ISSUE TITLE
git-cms-rmpkg

### ISSUE THREAD

**Issue by ktf** [cms-sw/cms-git-tools#1]
Simply removing the package from the local checkout area, now, will mean that the user wants to remove a given package. We need a git-cms-rmpkg which does the following:
- reset the given package to the original CMSSW_VERSION tag.
- removes the packages entry from `.git/info/sparse-checkout`
- invokes read-tree again.

**Comment by smuzaffar** [comment]
done https://github.com/cms-sw/cms-git-tools/pull/96
