### ISSUE TITLE
please create a "public" OAuth API key

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cms-git-tools#64]
git-cms-init uses the GitHub [API](https://developer.github.com/v3/) to check if a user has properly setup his or her repository.
Anonymous queries are limited to [60 per hour](https://developer.github.com/v3/#rate-limiting) per machine - which may sometimes become a problem on shared machines like lxplus.
Authenticated queries have a much higher limit (5000 per hour), making it much less lilely to run into it.

Would it be possible to create one "public" API key for the cms-sw user, without any access to [any scope](https://developer.github.com/v3/oauth/#scopes), to be used by the git-cms-init queries ?

For the moment I will set it up to use a similar key for my account, but it would be more sensible to have one from cms-sw.

**Comment by fwyzard** [comment]
Please create a "public" OAuth API key, and update the cms-git-tools scripts.
I plan to remove current OAuth key from my account in September.

**Comment by smuzaffar** [comment]
@fwyzard , thanks for providing your APi token. Although https://github.com/cms-sw/cms-git-tools/pull/112 now uses cmsbot token but can you please keep your token around for few months. There might be cmssw installations with old cms-git-tools which might need it.

**Comment by smuzaffar** [comment]
@fwyzard , looks like we have to deploy the token in some other way as git does not like committing the token in any github repos. Here is message I have received from github [a].

How about we use base64 decoing?

[a]
```
We noticed that a valid OAuth access token of yours was committed to a GitHub repository.
As a precautionary measure, we have revoked the OAuth token
```

**Comment by fwyzard** [comment]
Interesting... must be some new check they added

**Comment by fwyzard** [comment]
> How about we use base64 encoding/decoding?

Sure, anything simple should be fine.
