### ISSUE TITLE
Do not use /dev/stdout or stderr, running under sudo fails with permission errors.

### ISSUE THREAD

**Issue by dmitrijus** [cms-sw/cms-git-tools#71]
Hi,

The scripts should not use /dev/stderr for redirection,
It's a bad practice and it causes troubles for sudo/cron/whatever users (Permission denied).

This happens because:

```
echo a >&2
echo a >/dev/stderr 
```

are different - the later will try to open a file named /dev/stderr and it will fail,
because the sudo user does not have the access rights to the pts.
In other words, &2 can be duplicated and written to it, but it cannot be re-openned.

The "workaround" is to run the scripts either with -q option,
or create virtual stdin/stdout via redirection: `git-cms-init -ssh 2>&1 | cat` .

Ideally, scripts should never open /dev/stderr or /dev/stdout, but if the redirection is necessary,
it should be done via exec:
`echo a >somefile` should become 
`exec  >somefile; echo a`
or if some special stream is necesarry, `exec 5>test; echo "hello" >&5`

I can modify the scripts to remove "git-command >DEBUG_STREAM" style redirections,
reimplement "-q" and similar options via "exec 1> /dev/null". That might change the output
and I have no idea whether it won't break other scripts.

Dmitrijus

**Comment by fwyzard** [comment]
Partially addressed by #78 .

**Comment by fwyzard** [comment]
@dmitrijus is this still an issue ?

**Comment by dmitrijus** [comment]
I did a quick check it and it seems to work fine.
Thanks.
